#: import C kivy.utils.get_color_from_hex

# Se crearán dos constantes para los colores de los botones

#: set hexCOR_FUNDO_BT C("#000000") # NUMERICOS
#: set hexCOR_FUNDO_BT_BORD C("#151515") # NUMERICOS_CLICK
#: set hexCOR_FUNDO_BT_SPECIAL C("#000000") # OPERACIONES
#: set hexCOR_FUNDO_BT_SPECIAL_2 C("#151515") # OPERACIONES_CLICK
#: set hexCOR_FUNDO_BT_SPECIAL_R C("#000000") # OTROS
#: set hexCOR_FUNDO_BT_SPECIAL_R2 C("#151515") # OTROS_CLICK


# Se crearán varias clases de botones cada uno con el estilo del botón correspondiente


#BOTENES NUMERICOS
<CustomButton@Button>:
    font_size: "30sp"
    color: C("FFFFFF")
    background_color: 0,0,0,0

    # Se ejecuta antes que se instancien los botones
    canvas.before:
        Color:
            rgba: hexCOR_FUNDO_BT if self.state == "normal" else hexCOR_FUNDO_BT_BORD

        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [500,500]

#BOTONES ESPECIALES
<CustomButtonSpecial@Button>:
    font_size: "30sp"
    color: C("#FF9300")
    background_color: 0,0,0,0

    canvas.before:
        Color:
            rgba: hexCOR_FUNDO_BT_SPECIAL if self.state == "normal" else hexCOR_FUNDO_BT_SPECIAL_2

        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [500,]

#BOTONES DE RECURSOS
<CustomButtonR@Button>:
    font_size: "30sp"
    color: C("FFFFFF")
    background_color: 0,0,0,0

    canvas.before:
        Color:
            rgba: hexCOR_FUNDO_BT_SPECIAL_R if self.state == "normal" else hexCOR_FUNDO_BT_SPECIAL_R2

        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [500,]

# BOTONES ADD
<CustomButtonAdd@Button>:
    font_size: "20sp"
    color: C("#5F5F5F")
    background_color: 0,0,0,0

    canvas.before:
        Color:
            rgba: hexCOR_FUNDO_BT_SPECIAL_R if self.state == "normal" else hexCOR_FUNDO_BT_SPECIAL_R2

        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [500,]



#
#
#
#
#
#
#
#### Se determinará un GridLayout con 5 lineas o filas correspondiente
#### a cada uno de los componentes de nuestra calculadora

<WindowSimple@GridLayout>:
    rows: 6
    padding: "5sp"
    spacing: "5sp"

    # Se determina un BoxLayout en cada linea de nuestro GridLayout

#### TextInput
    BoxLayout:
        spacing: "7sp"
        size_hint: 2.,2.
        TextInput:
            # Para referirse a la caja de texto como tal
            id: ti_entrada
            text: "0"
            font_size: "50sp"
            size_hint: 1.02 ,1.02
            pos_hint: {"x": 0, "top": .5}
            multiline: False
            readonly: True
            background_color: C("000000")
            foreground_color: C("FFFFFF")
            halign: "right"

#### Botones (AC, C, %, /)
    BoxLayout:
        spacing: "7sp"
        size_hint: 1.,1.
        CustomButtonSpecial:
            text: "AC"
            on_press: ti_entrada.text = "0"
        CustomButtonSpecial:
            text: "<"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, 1))
        CustomButtonSpecial:
            text: "%"
            on_press: ti_entrada.text += self.text
        CustomButtonSpecial:
            text: "\u00F7"
            on_press: ti_entrada.text += self.text

#### BOTONES (7, 8 ,9 *)
    BoxLayout:
        spacing: "7sp"
        size_hint: 1.,1.
        CustomButton:
            text: "7"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "8"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "9"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButtonSpecial:
            text: u"\u00D7"
            on_press: ti_entrada.text += self.text

#### BOTONES(4, 5, 6, -)
    BoxLayout:
        spacing: "7sp"
        size_hint: 1.,1.
        CustomButton:
            text: "4"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "5"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "6"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButtonSpecial:
            text: "-"
            on_press: ti_entrada.text += self.text


#### BOTONES(1, 2, 3, +)
    BoxLayout:
        spacing: "7sp"
        CustomButton:
            text: "1"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "2"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "3"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButtonSpecial:
            text: "+"
            on_press: ti_entrada.text += self.text

#### BOTONES(0, ., =)
    BoxLayout:
        spacing: "7sp"
        size_hint: 1.,1.
        pos_hint: {"x": 0., "top": 0.}
        CustomButtonSpecial:
            text: "<-"
            on_press: root.on_press_bt()
        CustomButton:
            text: "0"
            on_press: ti_entrada.text += self.text
        CustomButton:
            text: "."
            on_press: ti_entrada.text += self.text
        CustomButtonSpecial:
            text: "="
            on_press: ti_entrada.text = str(app.evaluate(ti_entrada.text))
#########
#########
#
#
#OTHER FUNCTION ###########
#
#
##########
##########
<Otherfunction@GridLayout>
    rows: 8
    padding: "5sp"
    spacing: "5sp"
#### TextInput
    BoxLayout:
        spacing: "7sp"
        size_hint: 2.,2.
        TextInput:
            # Para referirse a la caja de texto como tal
            id: ti_entrada
            text: "0"
            font_size: "50sp"
            size_hint: 1. ,1.
            pos_hint: {"x": 0, "top": .6}
            multiline: False
            readonly: True
            background_color: C("000000")
            foreground_color: C("FFFFFF")
            halign: "right"

#### Botones (2nd, deg, sin, cos, tan)
    BoxLayout:
        spacing: "7sp"
        size_hint: 1.,1.

        CustomButtonAdd:
            text: "2nd"
            on_press: ti_entrada.text = "0"
        CustomButtonAdd:
            text: "deg"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, 1))
        CustomButtonAdd:
            text: "sin"
            on_press: ti_entrada.text += self.text
        CustomButtonAdd:
            text: "cos"
            on_press: ti_entrada.text += self.text
        CustomButtonAdd:
            text: "tan"
            on_press: ti_entrada.text += self.text

#### Botones (x^y, lg, ln, (, ))
    BoxLayout:
        spacing: "7sp"
        size_hint: 1.,1.

        CustomButtonAdd:
            text: "x" + u"\u00B2"
            on_press: ti_entrada.text = "0"
        CustomButtonAdd:
            text: "lg"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, 1))
        CustomButtonAdd:
            text: "ln"
            on_press: ti_entrada.text += self.text
        CustomButtonAdd:
            text: "("
            on_press: ti_entrada.text += self.text
        CustomButtonAdd:
            text: ")"
            on_press: ti_entrada.text += self.text

#### Botones (ROOT, AC, C, %, /)
    BoxLayout:
        spacing: "7sp"
        size_hint: 1.,1.
        CustomButtonAdd:
            text: u"\u221A" + "x"
            on_press: ti_entrada.text = u"\u221A"
        CustomButtonSpecial:
            text: "AC"
            on_press: ti_entrada.text = "0"
        CustomButtonSpecial:
            text: "<"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, 1))
        CustomButtonSpecial:
            text: "%"
            on_press: ti_entrada.text += self.text
        CustomButtonSpecial:
            text: "\u00F7"
            on_press: ti_entrada.text += self.text

#### BOTONES (x!, 7, 8 ,9 *)
    BoxLayout:
        spacing: "7sp"
        size_hint: 1.,1.
        CustomButtonAdd:
            text: "x!"
            on_press: ti_entrada.text += self.text
        CustomButton:
            text: "7"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "8"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "9"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButtonSpecial:
            text: u"\u00D7"
            on_press: ti_entrada.text += self.text

#### BOTONES(1/x, 4, 5, 6, -)
    BoxLayout:
        spacing: "7sp"
        size_hint: 1.,1.
        CustomButtonAdd:
            text: "1/x"
            on_press: ti_entrada.text += self.text
        CustomButton:
            text: "4"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "5"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "6"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButtonSpecial:
            text: "-"
            on_press: ti_entrada.text += self.text

#### BOTONES(pi, 1, 2, 3, +)
    BoxLayout:
        spacing: "7sp"
        size_hint: 1.,1.
        CustomButtonAdd:
            text: 	u"\u03C0"
            on_press: ti_entrada.text += self.text
        CustomButton:
            text: "1"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "2"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "3"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButtonSpecial:
            text: "+"
            on_press: ti_entrada.text += self.text

#### BOTONES(0, ., =)
    BoxLayout:
        spacing: "7sp"
        size_hint: 1.,1.
        pos_hint: {"x": 0., "top": 0.}
        CustomButtonSpecial:
            text: "->"
            on_press: root.on_press_bt()
        CustomButton:
            text: "0"
            on_press: ti_entrada.text += self.text
        CustomButton:
            text: "."
            on_press: ti_entrada.text += self.text
        CustomButton:
            text: "="
            on_press: ti_entrada.text = str(app.evaluate(ti_entrada.text))