#: import C kivy.utils.get_color_from_hex

# Se crearán dos constantes para los colores de los botones

#: set hexCOR_FUNDO_BT C("373636") # NUMERICOS
#: set hexCOR_FUNDO_BT_BORD C("B2B2B2") # NUMERICOS_CLICK
#: set hexCOR_FUNDO_BT_SPECIAL C("FAA005") # OPERACIONES
#: set hexCOR_FUNDO_BT_SPECIAL_2 C("#FFC43B") # OPERACIONES_CLICK
#: set hexCOR_FUNDO_BT_SPECIAL_R C("#B8B8B8") # OTROS
#: set hexCOR_FUNDO_BT_SPECIAL_R2 C("D5D5D5") # OTROS_CLICK


# Se crearán varias clases de botones cada uno con el estilo del botón correspondiente


#BOTENES NUMERICOS
<CustomButton@Button>:
    font_size: "30sp"
    color: C("FFFFFF")
    background_color: 0,0,0,0

    # Se ejecuta antes que se instancien los botones
    canvas.before:
        Color:
            rgba: hexCOR_FUNDO_BT if self.state == "normal" else hexCOR_FUNDO_BT_BORD

        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [200,]

#BOTONES ESPECIALES
<CustomButtonSpecial@Button>:
    font_size: "30sp"
    color: C("FFFFFF")
    background_color: 0,0,0,0

    canvas.before:
        Color:
            rgba: hexCOR_FUNDO_BT_SPECIAL if self.state == "normal" else hexCOR_FUNDO_BT_SPECIAL_2

        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [200,]

#BOTONES DE RECURSOS
<CustomButtonR@Button>:
    font_size: "30sp"
    color: C("000000")
    background_color: 0,0,0,0

    canvas.before:
        Color:
            rgba: hexCOR_FUNDO_BT_SPECIAL_R if self.state == "normal" else hexCOR_FUNDO_BT_SPECIAL_R2

        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [200,]

#
#
#
#
#
#
#
#### Se determinará un GridLayout con 5 lineas o filas correspondiente
#### a cada uno de los componentes de nuestra calculadora

<MiCalculadora@GridLayout>:
    rows: 6
    padding: "5sp"
    spacing: "5sp"

    # Se determina un BoxLayout en cada linea de nuestro GridLayout

#### TextInput
    BoxLayout:
        spacing: "7sp"
        size_hint: 2.,2.
        TextInput:
            id: ti_entrada
            text: "0"
            font_size: "50sp"
            size_hint: 1.02 ,1.02
            pos_hint: {"x": 0, "top": .5}
            multiline: False
            readonly: True
            background_color: C("000000")
            foreground_color: C("FFFFFF")
            halign: "right"

#### Botones (AC, C, %, /)
    BoxLayout:
        spacing: "7sp"
        size_hint: 1.,1.
        CustomButtonR:
            text: "AC"
            on_press: ti_entrada.text = "0"
        CustomButtonR:
            text: "C"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, 1))
        CustomButtonR:
            text: "%"
            on_press: ti_entrada.text += self.text
        CustomButtonSpecial:
            text: "\u00F7"
            on_press: ti_entrada.text += self.text

#### BOTONES (7, 8 ,9 *)
    BoxLayout:
        spacing: "7sp"
        size_hint: 1.,1.
        CustomButton:
            text: "7"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "8"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "9"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButtonSpecial:
            text: "*"
            on_press: ti_entrada.text += self.text

#### BOTONES(4, 5, 6, -)
    BoxLayout:
        spacing: "7sp"
        size_hint: 1.,1.
        CustomButton:
            text: "4"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "5"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "6"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButtonSpecial:
            text: "-"
            on_press: ti_entrada.text += self.text


#### BOTONES(1, 2, 3, +)
    BoxLayout:
        spacing: "7sp"
        CustomButton:
            text: "1"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "2"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButton:
            text: "3"
            on_press: ti_entrada.text = str(app.ini(ti_entrada.text, None)) + self.text
        CustomButtonSpecial:
            text: "+"
            on_press: ti_entrada.text += self.text

#### BOTONES(0, ., =)
    BoxLayout:
        spacing: "7sp"
        size_hint: 1.,1.
        pos_hint: {"x": 0., "top": 0.}
        Button:
            text: "0"
            size_hint: 2.,1.
            font_size: "30sp"
            color: C("FFFFFF")
            background_color: 0,0,0,0

            canvas.before:
                Color:
                    rgba: hexCOR_FUNDO_BT if self.state == "normal" else hexCOR_FUNDO_BT_BORD

                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [30,]
            on_press: ti_entrada.text += self.text
        CustomButton:
            text: "."
            on_press: ti_entrada.text += self.text
        CustomButtonSpecial:
            text: "="
            on_press: ti_entrada.text = str(app.evaluate(ti_entrada.text))


MiCalculadora: